### PR TITLE
Fix default .tenonrc file read bug.

### PR DESCRIPTION
**Pull request by kevinlambert**
The default .tenonrc file was never been read into the options.

### CODE REVIEW

**Comment by egauci** [comment]
Hi, is there a symptom you are trying to fix? The code in tenon-api-client should be reading the configuration from the passed "config" parameter. Is it failing to do so?

I just tested and it works for me. Please let me know if you are seeing an issue.

**Comment by kevinlambert** [comment]
Hi. My understanding is that configuration put into the .tenonrc file in the root directory should be read and used. But no where in the code does it actually read the file.

**Comment by egauci** [comment]
gulp-tenon-client passes the filename to [tenon-api-client](https://github.com/egauci/tenon-api-client), which is responsible for merging it in with other options.

Most of the work is done in tenon-api-client, this repo is just the gulp scaffolding.

**Comment by egauci** [comment]
Thank you for your input, but I think this request was based on a misunderstanding and does not actually add functionality.

**Comment by kevinlambert** [comment]
sorry. It seems there was a problem with the tenon service and not the gulp file. thanks.

**Pull request closed without merging**
